# Generated by Django 5.2.4 on 2025-08-11 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('silant_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='service_company',
        ),
    ]
