# Generated by Django 5.2.4 on 2025-08-18 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silant_app', '0002_remove_maintenance_service_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='service_company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='silant_app.servicecompany', verbose_name='Сервисная компания'),
        ),
    ]
