# Generated by Django 5.2.4 on 2025-08-19 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silant_app', '0004_alter_maintenance_service_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamation',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamations', to='silant_app.machine', verbose_name='Машина'),
        ),
    ]
